# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Tools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tools
  pod 'Masonry'
  
  pod 'SDWebImage'
  
  pod 'Charts'

  pod 'YJPodTest', :git => 'https://github.com/Manchitor/YJPodTest.git'
end
